name: Deploy AlwaysData

on:
  push:
    branches:
      - RAMA_MGM

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Sincronizar archivos vía FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ftp-misaelgaray.alwaysdata.net 
          username: misaelgaray
          password: Mgm1927.
          server-dir: www/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
